// screens/prebuilt/prebuiltSessions.ts
import type { Prebuilt } from "./prebuiltConfig";

export const PREBUILT_SESSIONS: Prebuilt[] = [
  // ============================================================
  // ACTIVATION — Routines pré-entraînement / pré-match
  // ============================================================
  {
    category: "ACTIVATION",
    title: "Réveil musculaire express",
    intensity: "easy",
    duration: "8-10 min",
    objective: "Booste ton explosivité dès le réveil",
    focus: "mobility",
    location: "home",
    equipment: [],
    tags: ["Express", "Matin", "Activation"],
    level: "Tout niveau",
    detail: [
      "Cat-camel: 8 répétitions lentes — À 4 pattes, alterne dos rond (chat) et dos creux (chameau)",
      "World's greatest stretch: 5 / côté — Fente avant + rotation du buste, bras vers le ciel",
      "Leg swings: 10 / jambe — Balancier jambe tendue avant-arrière puis latéral, mains sur un mur",
      "Pogos légers: 2 x 15 rebonds — Petits sauts sur place, chevilles rigides, contacts au sol rapides",
      "A-skip sur place: 2 x 10 / jambe — Montée de genou dynamique avec petit saut, bras opposé",
    ],
    expectations: [
      "Mouvement fluide, pas de force.",
      "Respiration calme, relâchement.",
      "Objectif = réveiller, pas fatiguer.",
    ],
  },
  {
    category: "ACTIVATION",
    title: "Warm-up terrain complet",
    intensity: "easy",
    duration: "12-15 min",
    objective: "L'échauffement pro pour performer dès la 1ère minute",
    focus: "mobility",
    location: "pitch",
    equipment: [],
    tags: ["Terrain", "Complet", "Standard"],
    level: "Tout niveau",
    detail: [
      "Footing léger: 3-4 min",
      "Mobilité dynamique: hanches, chevilles, épaules (2 min)",
      "Gammes athlétiques: montées de genoux, talons-fesses, pas chassés (3 min)",
      "Accélérations progressives: 4 x 30 m (60-70-80-90%)",
      "Étirements actifs: 1 min",
    ],
    expectations: [
      "Progressif du début à la fin.",
      "Terminer avec une légère sudation.",
      "Pas d'étirements statiques prolongés.",
    ],
  },
  {
    category: "ACTIVATION",
    title: "Activation neuro pré-vitesse",
    intensity: "moderate",
    duration: "10-12 min",
    objective: "Déverrouille ta vitesse max avant les sprints",
    focus: "speed",
    location: "pitch",
    equipment: ["Cônes"],
    tags: ["Vitesse", "Neuro", "Explosif"],
    level: "Amateur / semi-pro",
    detail: [
      "Pogo hops: 2 x 20 — Sauts chevilles rigides, contacts ultra-rapides au sol, mollets actifs",
      "A-skip dynamiques: 2 x 20 m — Montées de genoux alternées avec impulsion, bras coordonnés",
      "High knees rapides: 2 x 10 m — Montées de genoux fréquence max, rester sur les orteils",
      "Falling starts: 4 x 10 m — Départ en déséquilibre avant, laisser tomber puis sprinter",
      "Sprint progressif: 2 x 20 m @ 85-90% — Accélération contrôlée sans forcer au max",
    ],
    expectations: [
      "Contacts au sol ultra-courts.",
      "Récup complète entre les sprints.",
      "Qualité > quantité.",
    ],
  },
  {
    category: "ACTIVATION",
    title: "Activation force pré-salle",
    intensity: "easy",
    duration: "8-10 min",
    objective: "Préparer muscles et articulations avant la muscu",
    focus: "strength",
    location: "gym",
    equipment: ["Élastiques"],
    tags: ["Salle", "Force", "Préparation"],
    level: "Tout niveau",
    detail: [
      "Foam roller: 2 min — Rouleau sur cuisses avant/arrière et fessiers pour détendre les muscles",
      "Band pull-apart: 2 x 15 — Élastique devant toi, écarte les bras en serrant les omoplates",
      "Goblet squat léger: 2 x 8 — Squat avec poids (ou sans) tenu contre la poitrine",
      "Hip circle: 10 / côté — Debout, dessine des cercles avec le genou en l'air",
      "Glute bridge: 2 x 10 — Allongé dos au sol, monte le bassin en serrant les fessiers",
    ],
    expectations: [
      "Pas de charge lourde.",
      "Sentir les muscles s'activer.",
      "Prêt à soulever après ça.",
    ],
  },

  // ============================================================
  // RÉCUPÉRATION — Routines post-effort
  // ============================================================
  {
    category: "RÉCUPÉRATION",
    title: "Cooldown post-entraînement",
    intensity: "easy",
    duration: "10-12 min",
    objective: "Récupère 2x plus vite après l'effort",
    focus: "mobility",
    location: "pitch",
    equipment: [],
    tags: ["Post-training", "Cooldown", "Standard"],
    level: "Tout niveau",
    detail: [
      "Marche ou footing très léger: 3-4 min — Redescendre le cardio progressivement",
      "Respiration ventrale: 10 cycles — Inspir 4s par le nez, expir 6s par la bouche, ventre qui gonfle",
      "Étirements légers: 30\" chaque — Cuisses, arrière des cuisses, mollets tenus sans forcer",
      "Hip flexor stretch: 30\" / côté — Genou au sol, hanche avant, sentir l'étirement devant la hanche",
      "Child's pose: 1 min — À genoux, assis sur les talons, bras tendus devant, front au sol",
    ],
    expectations: [
      "Rythme cardiaque qui redescend.",
      "Pas de douleur dans les étirements.",
      "Sortir détendu, pas épuisé.",
    ],
  },
  {
    category: "RÉCUPÉRATION",
    title: "Récup active J+1",
    intensity: "easy",
    duration: "20-25 min",
    objective: "Efface les courbatures, reviens plus frais demain",
    focus: "mobility",
    location: "home",
    equipment: ["Tapis"],
    tags: ["Lendemain", "Actif", "Circulation"],
    level: "Tout niveau",
    detail: [
      "Marche ou vélo très léger: 8-10 min — Cardio minimal pour faire circuler le sang",
      "90/90 switches: 3 x 6 / côté — Assis, jambes à 90°, bascule d'un côté à l'autre sans les mains",
      "Foam roller: 2 min — Roule sur les zones tendues pour détendre les muscles",
      "Étirements doux: 5 min — Tiens chaque position 30-45s sans forcer",
      "Respiration 4-7-8: 5 cycles — Inspir 4s, blocage 7s, expir lente 8s pour te relaxer",
    ],
    expectations: [
      "Zéro intensité, zéro fatigue.",
      "Bouger pour mieux récupérer.",
      "Écouter son corps, adapter si besoin.",
    ],
  },
  {
    category: "RÉCUPÉRATION",
    title: "Récup post-match complète",
    intensity: "easy",
    duration: "25-30 min",
    objective: "Le protocole pro pour enchaîner les matchs sans fatigue",
    focus: "mobility",
    location: "home",
    equipment: ["Tapis", "Foam roller"],
    tags: ["Post-match", "Complet", "Récupération"],
    level: "Tout niveau",
    detail: [
      "Hydratation + collation protéinée — Eau + shaker ou yaourt grec, à prendre en parallèle",
      "Marche légère: 5 min — Redescends le rythme cardiaque tranquillement",
      "Foam roller complet: 8 min — Roule cuisses avant/arrière, intérieur, mollets pour évacuer les tensions",
      "Étirements passifs: 10 min — Maintiens chaque position 30-45s, respire dans l'étirement",
      "Respiration profonde: 3 min — Yeux fermés, inspir lente, expir lente, relâche tout",
      "Douche contrastée: conseillée après — Alterne 30s chaud / 30s froid pour activer la récup",
    ],
    expectations: [
      "Faire dans les 2h après le match.",
      "Ne pas forcer sur les étirements.",
      "Priorité = circulation + relâchement.",
    ],
  },
  {
    category: "RÉCUPÉRATION",
    title: "Routine sommeil & récup",
    intensity: "easy",
    duration: "10-12 min",
    objective: "Dors mieux, régénère tes muscles pendant la nuit",
    focus: "mobility",
    location: "home",
    equipment: ["Tapis"],
    tags: ["Sommeil", "Soir", "Relaxation"],
    level: "Tout niveau",
    detail: [
      "Lumière tamisée, écrans éteints — Prépare ton cerveau au sommeil",
      "Child's pose: 1 min — À genoux, assis sur les talons, bras tendus devant, front au sol",
      "Happy baby: 1 min — Sur le dos, attrape tes pieds, genoux vers les aisselles, bascule doucement",
      "Supine twist: 30\" / côté — Allongé, genoux pliés qui tombent d'un côté, regard à l'opposé",
      "Legs up the wall: 3 min — Allongé, jambes verticales contre le mur, détend tout",
      "Respiration 4-7-8: 8 cycles — Inspir 4s, blocage 7s, expir 8s pour ralentir le système nerveux",
      "Body scan mental: 2 min — Allongé, scanne ton corps de la tête aux pieds en relâchant chaque zone",
    ],
    expectations: [
      "Faire 30-60 min avant de dormir.",
      "Environnement calme et frais.",
      "Laisser les pensées passer.",
    ],
  },

  // ============================================================
  // MOBILITÉ EXPRESS — Routines courtes (5-15 min)
  // ============================================================
  {
    category: "MOBILITÉ EXPRESS",
    title: "Flow hanches 8 min",
    intensity: "easy",
    duration: "8 min",
    objective: "Gagne en amplitude pour des frappes plus puissantes",
    focus: "mobility",
    location: "home",
    equipment: [],
    tags: ["Hanches", "Express", "Quotidien"],
    level: "Tout niveau",
    detail: [
      "90/90 position: 30\" / côté — Assis, une jambe devant à 90°, l'autre derrière à 90°, buste droit",
      "90/90 switches: 8 transitions — Bascule d'un côté à l'autre en gardant les genoux au sol",
      "Hip circles: 8 / côté — Debout sur une jambe, dessine des cercles avec le genou levé",
      "Pigeon stretch: 45\" / côté — Une jambe pliée devant, l'autre tendue derrière, descends le buste",
      "Deep squat hold: 1 min — Squat complet, talons au sol, coudes qui écartent les genoux",
    ],
    expectations: [
      "Respiration calme.",
      "Aucune douleur vive.",
      "Idéal le matin ou après position assise.",
    ],
  },
  {
    category: "MOBILITÉ EXPRESS",
    title: "Flow chevilles 6 min",
    intensity: "easy",
    duration: "6 min",
    objective: "Préviens les entorses et améliore tes appuis",
    focus: "mobility",
    location: "home",
    equipment: [],
    tags: ["Chevilles", "Express", "Appuis"],
    level: "Tout niveau",
    detail: [
      "Ankle circles: 10 / côté / sens — Pied en l'air, dessine des cercles avec les orteils",
      "Dorsiflexion murale: 15 / côté — Face au mur, genou qui pousse vers le mur sans lever le talon",
      "Calf raises lents: 12 — Monte sur la pointe des pieds 2s, redescends 2s, contrôle total",
      "Single leg balance: 30\" / côté — Debout sur une jambe, yeux fixes devant, ne pas trembler",
      "Tib raises: 15 — Dos contre un mur, lève la pointe des pieds vers toi, muscle le tibia",
    ],
    expectations: [
      "Sentir l'étirement devant le tibia.",
      "Contrôle sur les raises.",
      "Essentiel pour les sprints et changements de direction.",
    ],
  },
  {
    category: "MOBILITÉ EXPRESS",
    title: "Flow T-spine 7 min",
    intensity: "easy",
    duration: "7 min",
    objective: "Libère ton dos pour des rotations plus fluides",
    focus: "mobility",
    location: "home",
    equipment: [],
    tags: ["Dos", "Rotation", "Posture"],
    level: "Tout niveau",
    detail: [
      "Cat-camel: 8 reps — À 4 pattes, alterne dos rond (chat) puis dos creux (chameau)",
      "Thread the needle: 6 / côté — À 4 pattes, passe un bras sous le corps, épaule au sol, tourne le buste",
      "Open book: 6 / côté — Sur le côté, ouvre le bras du dessus en tournant le buste, regard suit la main",
      "Prone Y-T-W: 6 de chaque — Ventre au sol, dessine Y puis T puis W avec les bras, omoplates serrées",
      "Child's pose avec rotation: 30\" / côté — Position de l'enfant avec un bras qui pousse sur le côté",
    ],
    expectations: [
      "Rotation thoracique, pas lombaire.",
      "Épaules détendues.",
      "Parfait après une journée de bureau.",
    ],
  },
  {
    category: "MOBILITÉ EXPRESS",
    title: "Réveil complet 10 min",
    intensity: "easy",
    duration: "10 min",
    objective: "10 min le matin = énergie toute la journée",
    focus: "mobility",
    location: "home",
    equipment: [],
    tags: ["Matin", "Full body", "Réveil"],
    level: "Tout niveau",
    detail: [
      "Au lit: 1 min — Étire bras au-dessus de la tête, jambes tendues, bâille un bon coup",
      "Cat-camel: 8 — À 4 pattes, alterne dos rond (chat) puis dos creux (chameau)",
      "World's greatest stretch: 5 / côté — Fente avant + rotation du buste, bras vers le ciel",
      "Squat to stand: 8 — Attrape tes orteils, tends les jambes, puis descends en squat complet",
      "Shoulder circles + neck rolls: 1 min — Grands cercles d'épaules + rotations douces de la nuque",
      "Jumping jacks légers: 20 — Sauts écartés bras en l'air, version tranquille pour se réveiller",
    ],
    expectations: [
      "Progressif, pas brutal.",
      "Hydratation avant ou pendant.",
      "Donne de l'énergie pour la journée.",
    ],
  },
  {
    category: "MOBILITÉ EXPRESS",
    title: "Pause bureau 5 min",
    intensity: "easy",
    duration: "5 min",
    objective: "Annule les dégâts de la chaise de bureau",
    focus: "mobility",
    location: "home",
    equipment: [],
    tags: ["Bureau", "Assis", "Pause"],
    level: "Tout niveau",
    detail: [
      "Standing hip flexor stretch: 30\" / côté — Grand pas en avant, bassin vers l'avant, étire le psoas",
      "Chest opener: 30\" — Mains derrière la tête, coudes en arrière, ouvre la poitrine",
      "Neck stretches: 20\" / côté — Oreille vers l'épaule, main qui tire doucement, étire le cou",
      "Standing figure-4: 30\" / côté — Debout, cheville sur le genou opposé, descends les fesses",
      "10 squats légers — Squats poids du corps pour réactiver la circulation dans les jambes",
    ],
    expectations: [
      "Faire toutes les 2h si possible.",
      "Debout, près du bureau.",
      "Empêche les raideurs de s'installer.",
    ],
  },

  // ============================================================
  // PRÉVENTION — Protocoles ciblés anti-blessures
  // ============================================================
  {
    category: "PRÉVENTION",
    title: "Protocole ischios (Nordic)",
    intensity: "moderate",
    duration: "15-18 min",
    objective: "Divise par 2 ton risque de claquage",
    focus: "strength",
    location: "home",
    equipment: ["Tapis", "Point d'ancrage"],
    tags: ["Ischios", "Nordic", "Excentrique"],
    level: "Amateur / semi-pro",
    detail: [
      "Hip hinge drill: 2 x 8 — Debout, pousse les fesses en arrière en gardant le dos plat, genoux légèrement fléchis",
      "Glute bridge: 2 x 12 — Allongé, genoux pliés, monte le bassin en serrant les fessiers",
      "Nordic curl assisté: 4 x 4 — À genoux, quelqu'un tient tes chevilles, descends lentement 3-4s en freinant",
      "Single leg RDL: 3 x 6 / côté — Debout sur une jambe, penche le buste en avant, jambe arrière tendue",
      "Hamstring stretch: 30\" / côté — Jambe tendue devant, penche le buste vers le pied, étire l'arrière de la cuisse",
    ],
    expectations: [
      "Contrôle de la descente = clé.",
      "Adapter l'assistance selon le niveau.",
      "2-3x / semaine pour résultats.",
    ],
  },
  {
    category: "PRÉVENTION",
    title: "Protocole adducteurs",
    intensity: "moderate",
    duration: "15-18 min",
    objective: "Protège-toi de la pubalgie, le fléau des footeux",
    focus: "strength",
    location: "home",
    equipment: ["Tapis"],
    tags: ["Adducteurs", "Pubalgie", "Prévention"],
    level: "Amateur / semi-pro",
    detail: [
      "Adductor rockback: 2 x 10 — À 4 pattes, une jambe tendue sur le côté, recule les fesses vers les talons",
      "Copenhagen plank: 3 x 15-20\" / côté — Planche latérale, jambe du dessus sur un banc, l'autre en l'air",
      "Sumo squat: 3 x 10 — Squat pieds très écartés, pointes vers l'extérieur, descends profond",
      "Side lunge: 2 x 8 / côté — Grand pas latéral, une jambe pliée, l'autre tendue, fesses en arrière",
      "Adductor stretch: 45\" / côté — Assis jambes écartées, penche vers une jambe, étire l'intérieur de la cuisse",
    ],
    expectations: [
      "Pas de douleur vive.",
      "Progression lente sur le Copenhagen.",
      "Essentiel pour les changements de direction.",
    ],
  },
  {
    category: "PRÉVENTION",
    title: "Protocole genoux (ACL)",
    intensity: "moderate",
    duration: "18-20 min",
    objective: "Blinde tes genoux contre les ruptures des croisés",
    focus: "strength",
    location: "home",
    equipment: ["Mini-band"],
    tags: ["Genou", "ACL", "Stabilité"],
    level: "Tout niveau",
    detail: [
      "Terminal knee extension: 2 x 15 / côté — Élastique derrière le genou, tends la jambe complètement, muscle le vaste",
      "Mini-band walks: 2 x 15 pas / direction — Élastique aux chevilles, marche en crabe, genoux écartés",
      "Single leg squat partiel: 3 x 8 / côté — Sur une jambe, descends légèrement en contrôlant l'alignement du genou",
      "Step down contrôlé: 3 x 8 / côté — Sur une marche, descends sur une jambe très lentement, contrôle le genou",
      "Balance instable: 3 x 30\" / côté — Debout sur un coussin ou serviette pliée, maintiens l'équilibre",
    ],
    expectations: [
      "Alignement genou-orteil = priorité.",
      "Pas d'effondrement vers l'intérieur.",
      "Progression lente et contrôlée.",
    ],
  },
  {
    category: "PRÉVENTION",
    title: "Protocole chevilles",
    intensity: "moderate",
    duration: "15 min",
    objective: "Fini les entorses qui gâchent ta saison",
    focus: "strength",
    location: "home",
    equipment: ["Mini-band"],
    tags: ["Chevilles", "Entorse", "Proprioception"],
    level: "Tout niveau",
    detail: [
      "Ankle circles: 15 / côté / sens — Pied en l'air, dessine des cercles lents avec les orteils",
      "Calf raises: 3 x 15 — Monte sur la pointe des pieds, redescends contrôlé, muscle les mollets",
      "Tib raises: 3 x 15 — Dos au mur, talons au sol, lève les orteils vers toi, muscle le tibia",
      "Single leg balance: 3 x 30\" / côté — Debout sur une jambe, yeux fixes, contrôle la stabilité",
      "Single leg hops: 2 x 10 / côté — Petits sauts sur place sur une jambe, réceptions stables",
      "Band inversion/eversion: 2 x 12 / côté — Élastique au pied, tourne la cheville dedans puis dehors",
    ],
    expectations: [
      "Essentiel après une entorse.",
      "Progression vers surfaces instables.",
      "Intégrer dans le warm-up régulier.",
    ],
  },
  {
    category: "PRÉVENTION",
    title: "Core anti-rotation football",
    intensity: "moderate",
    duration: "12-15 min",
    objective: "Gagne tes duels grâce à un gainage de pro",
    focus: "strength",
    location: "home",
    equipment: ["Élastique"],
    tags: ["Core", "Gainage", "Duels"],
    level: "Amateur / semi-pro",
    detail: [
      "Dead bug: 3 x 8 / côté — Sur le dos, bras en l'air, étends une jambe et le bras opposé sans cambrer",
      "Pallof press: 3 x 10 / côté — Élastique sur le côté, pousse les mains devant toi sans tourner le buste",
      "Side plank: 3 x 25\" / côté — Sur le coude, corps aligné, hanche haute, gainage latéral",
      "Bird dog: 3 x 8 / côté — À 4 pattes, tends un bras et la jambe opposée, dos plat",
      "Hollow hold: 3 x 20\" — Sur le dos, jambes et épaules décollées, bas du dos plaqué au sol",
    ],
    expectations: [
      "Dos plat, pas de cambrure.",
      "Gainage = résister au mouvement.",
      "Transfert direct sur le terrain.",
    ],
  },

  // ============================================================
  // MATCH DAY — Routines spécifiques jour de match
  // ============================================================
  {
    category: "MATCH DAY",
    title: "J-1 Match — Activation légère",
    intensity: "easy",
    duration: "20-25 min",
    objective: "Arrive au match frais et affûté comme un pro",
    focus: "mobility",
    location: "pitch",
    equipment: ["Cônes"],
    tags: ["J-1", "Activation", "Fraîcheur"],
    level: "Tout niveau",
    detail: [
      "Footing très léger: 5 min — Petit trot pour faire monter le cardio doucement",
      "Mobilité dynamique: 5 min — Rotations hanches, chevilles, épaules, mouvements amples",
      "Gammes courtes: 3 min — Montées de genoux, talons-fesses, pas chassés sur 10-15 m",
      "Accélérations progressives: 4-6 x 20 m — Monte à 80-85% max, jamais à fond la veille",
      "Étirements actifs: 2 min — Mouvements dynamiques, pas de positions tenues longtemps",
      "Visualisation: 2 min — Ferme les yeux et imagine tes actions clés du match à venir",
    ],
    expectations: [
      "RPE max = 4.",
      "Sortir activé, pas fatigué.",
      "Bonne nuit de sommeil après.",
    ],
  },
  {
    category: "MATCH DAY",
    title: "Warm-up pré-match terrain",
    intensity: "moderate",
    duration: "20-25 min",
    objective: "Sois 100% prêt dès le coup d'envoi",
    focus: "speed",
    location: "pitch",
    equipment: [],
    tags: ["Pré-match", "Échauffement", "Terrain"],
    level: "Tout niveau",
    detail: [
      "Footing collectif: 4-5 min — Tour de terrain ensemble, cardio progressif",
      "Mobilité dynamique: 3 min — Cercles de hanches, rotations chevilles, ouvertures de buste",
      "Gammes montantes: 4 min — Montées de genoux de plus en plus hautes, talons-fesses rapides, pas chassés",
      "Courses progressives: 3 x 40 m — Monte l'intensité: 70% puis 80% puis 90%",
      "Sprints courts: 3 x 15 m @ 95% — Explosivité quasi-max, réveille le système nerveux",
      "Activation contacts: 2-3 min — Petits duels d'épaules ou exercice technique avec ballon",
      "Focus mental: 1-2 min — Respire, visualise tes objectifs, entre dans ta bulle",
    ],
    expectations: [
      "Finir 5-8 min avant le coup d'envoi.",
      "Légère sudation = signe que c'est bon.",
      "Mental focus, pas de bavardage.",
    ],
  },
  {
    category: "MATCH DAY",
    title: "Routine mi-temps",
    intensity: "easy",
    duration: "5-7 min",
    objective: "Reste chaud et explosif pour la 2e mi-temps",
    focus: "mobility",
    location: "pitch",
    equipment: [],
    tags: ["Mi-temps", "Maintien", "Match"],
    level: "Tout niveau",
    detail: [
      "Rester debout/en mouvement — Ne t'assieds pas plus de 2-3 min, les muscles refroidissent vite",
      "Hydratation + nutrition — Petites gorgées d'eau, gel ou barre si besoin d'énergie",
      "Mobilité légère: 2 min — Cercles de hanches et chevilles debout, genoux hauts légers",
      "Accélérations courtes: 2-3 x 10 m — Petits sprints pour rester réactif",
      "Respiration + focus: 1 min — Inspire profond, expire lent, rappelle-toi tes objectifs",
    ],
    expectations: [
      "Ne pas se refroidir.",
      "Écouter le coach en bougeant.",
      "Reprendre le match aussi réactif qu'au début.",
    ],
  },
  {
    category: "MATCH DAY",
    title: "J+1 Match — Régénération",
    intensity: "easy",
    duration: "25-30 min",
    objective: "Régénère tes jambes pour être prêt dès lundi",
    focus: "mobility",
    location: "home",
    equipment: ["Tapis", "Foam roller"],
    tags: ["J+1", "Récupération", "Régénération"],
    level: "Tout niveau",
    detail: [
      "Marche ou vélo très léger: 10 min — Cardio minimal pour faire circuler le sang, FC sous 120 bpm",
      "Foam roller complet: 8-10 min — Roule cuisses, mollets, fessiers, dos, zones sensibles du match",
      "Mobilité douce: 5 min — Cercles de hanches, rotations du dos, bras, tout en douceur",
      "Étirements passifs légers: 5 min — Positions tenues 30-40s, respire dans l'étirement",
      "Respiration profonde: 2 min — Inspir 4s, expir 6s, active la récupération du système nerveux",
    ],
    expectations: [
      "Zéro intensité.",
      "Objectif = circulation + relâchement.",
      "Bien dormir le soir suivant.",
    ],
  },

  // ============================================================
  // PACK 7 JOURS — Programme mobilité progressif
  // ============================================================
  {
    category: "PACK 7 JOURS",
    title: "Jour 1 — Reset hanches",
    intensity: "easy",
    duration: "18-20 min",
    objective: "Débute ta transformation mobilité par les hanches",
    focus: "mobility",
    location: "home",
    equipment: [],
    tags: ["Pack 7J", "Jour 1", "Hanches"],
    level: "Tout niveau",
    detail: [
      "Respiration 90/90: 2 min — En position 90/90, respire profond pour détendre les hanches",
      "90/90 switches: 3 x 6 / côté — Assis jambes à 90°, bascule d'un côté à l'autre fluidement",
      "Hip circles: 10 / côté — Debout, genou levé, dessine des cercles amples avec le genou",
      "Pigeon stretch: 45\" / côté — Jambe avant pliée, jambe arrière tendue, descends le buste",
      "Deep squat hold: 2 x 45\" — Squat complet, talons au sol, coudes écartent les genoux",
    ],
    expectations: [
      "Premier jour = évaluation.",
      "Noter les zones raides.",
      "Pas de forcing.",
    ],
  },
  {
    category: "PACK 7 JOURS",
    title: "Jour 2 — T-spine & épaules",
    intensity: "easy",
    duration: "18-20 min",
    objective: "Améliorer la rotation thoracique et libérer les épaules",
    focus: "mobility",
    location: "home",
    equipment: [],
    tags: ["Pack 7J", "Jour 2", "Haut du corps"],
    level: "Tout niveau",
    detail: [
      "Cat-camel: 10 — À 4 pattes, alterne dos rond (chat) puis dos creux (chameau)",
      "Thread the needle: 8 / côté — À 4 pattes, passe un bras sous le corps, épaule au sol, tourne le buste",
      "Open book: 8 / côté — Sur le côté, ouvre le bras du dessus en tournant, regard suit la main",
      "Wall slides: 2 x 10 — Dos au mur, coudes et mains contre le mur, glisse les bras de haut en bas",
      "Doorway stretch: 30\" / côté — Avant-bras sur le cadre de porte, avance le buste, ouvre la poitrine",
    ],
    expectations: [
      "Rotation du thorax, pas du bassin.",
      "Épaules basses et détendues.",
      "Sentir l'ouverture de la cage thoracique.",
    ],
  },
  {
    category: "PACK 7 JOURS",
    title: "Jour 3 — Chaîne postérieure",
    intensity: "easy",
    duration: "20 min",
    objective: "Assouplir ischios et dos sans perdre de force",
    focus: "mobility",
    location: "home",
    equipment: [],
    tags: ["Pack 7J", "Jour 3", "Ischios"],
    level: "Tout niveau",
    detail: [
      "Hip hinge drill: 2 x 8 — Debout, pousse les fesses en arrière, dos plat, genoux légèrement fléchis",
      "Hamstring floss: 3 x 8 / côté — Sur le dos, jambe en l'air, tends et plie le genou alternativement",
      "Jefferson curl: 2 x 6 — Debout, enroule la colonne vertèbre par vertèbre, mains vers le sol",
      "Downward dog: 3 x 30\" — Mains et pieds au sol, fesses en l'air, talons qui poussent vers le sol",
      "Forward fold: 1 min — Debout, jambes tendues, penche le buste vers les pieds, relâche le haut du corps",
    ],
    expectations: [
      "Flexion à partir des hanches.",
      "Sensation d'étirement, pas de douleur.",
      "Ne pas arrondir excessivement le dos.",
    ],
  },
  {
    category: "PACK 7 JOURS",
    title: "Jour 4 — Chevilles & appuis",
    intensity: "easy",
    duration: "18 min",
    objective: "Améliorer la mobilité et stabilité des chevilles",
    focus: "mobility",
    location: "home",
    equipment: [],
    tags: ["Pack 7J", "Jour 4", "Chevilles"],
    level: "Tout niveau",
    detail: [
      "Ankle circles: 15 / côté / sens — Pied en l'air, dessine des cercles lents avec les orteils",
      "Dorsiflexion murale: 3 x 12 / côté — Face au mur, genou qui pousse vers le mur sans lever le talon",
      "Calf raises lents: 3 x 12 — Monte sur la pointe des pieds 2s, redescends 2s, contrôle total",
      "Tib raises: 2 x 15 — Dos au mur, talons au sol, lève les orteils vers toi",
      "Single leg balance: 3 x 30\" / côté — Debout sur une jambe, yeux fixes, maintiens l'équilibre",
    ],
    expectations: [
      "Genou qui dépasse les orteils = objectif.",
      "Contrôle sur toute l'amplitude.",
      "Fondamental pour les sprints.",
    ],
  },
  {
    category: "PACK 7 JOURS",
    title: "Jour 5 — Adducteurs & plan frontal",
    intensity: "easy",
    duration: "18 min",
    objective: "Préparer les adducteurs aux changements de direction",
    focus: "mobility",
    location: "home",
    equipment: [],
    tags: ["Pack 7J", "Jour 5", "Adducteurs"],
    level: "Tout niveau",
    detail: [
      "Adductor rockback: 3 x 10 — À 4 pattes, une jambe tendue sur le côté, recule les fesses vers les talons",
      "Cossack squat: 3 x 6 / côté — Squat latéral profond, une jambe pliée, l'autre tendue sur le côté",
      "Side lunge: 2 x 8 / côté — Grand pas latéral, une jambe pliée, l'autre tendue, fesses en arrière",
      "Frog stretch: 2 x 45\" — À 4 pattes, genoux très écartés, pousse les fesses en arrière",
      "Butterfly stretch: 1 min — Assis, plantes de pieds jointes, genoux qui tombent vers le sol",
    ],
    expectations: [
      "Aller chercher l'amplitude progressivement.",
      "Pas de rebond.",
      "Zone souvent négligée mais cruciale.",
    ],
  },
  {
    category: "PACK 7 JOURS",
    title: "Jour 6 — Flow complet",
    intensity: "easy",
    duration: "22-25 min",
    objective: "Le flow ultime : ton corps bouge comme jamais",
    focus: "mobility",
    location: "home",
    equipment: [],
    tags: ["Pack 7J", "Jour 6", "Flow"],
    level: "Tout niveau",
    detail: [
      "Sun salutation modifié: 3 cycles — Mains en l'air → penche → planche → chien tête en bas → fente → debout",
      "World's greatest stretch flow: 5 / côté — Fente avant + rotation du buste + coude au sol, enchaîne fluide",
      "Squat to stand: 10 — Attrape tes orteils, tends les jambes, puis descends en squat complet",
      "Lunge with rotation: 6 / côté — Grande fente avant, tourne le buste vers la jambe avant",
      "Hip flow: 3 cycles — Enchaîne position 90/90 → pigeon → squat profond sans t'arrêter",
      "Standing balance flow: 2 min — Debout sur une jambe, mouvements de bras et jambe libres, change de côté",
    ],
    expectations: [
      "Enchaîner sans pause.",
      "Respiration fluide.",
      "Sentir le corps bouger comme un tout.",
    ],
  },
  {
    category: "PACK 7 JOURS",
    title: "Jour 7 — Reset & bilan",
    intensity: "easy",
    duration: "20-22 min",
    objective: "Mesure tes progrès et consolide tes gains",
    focus: "mobility",
    location: "home",
    equipment: [],
    tags: ["Pack 7J", "Jour 7", "Bilan"],
    level: "Tout niveau",
    detail: [
      "Test hanches: 90/90 — Assis jambes à 90°, note si c'est plus facile qu'au jour 1",
      "Test T-spine: rotation — Allongé, mesure jusqu'où tes épaules touchent le sol en tournant",
      "Test chevilles: dorsiflexion — Genou au mur, note la distance pied-mur sans lever le talon",
      "Flow libre: 10 min — Bouge librement, insiste sur les zones encore raides",
      "Respiration + visualisation: 3 min — Ferme les yeux, respire, visualise ton corps plus mobile",
    ],
    expectations: [
      "Comparer avec le jour 1.",
      "Noter les progrès.",
      "Identifier les zones à travailler.",
    ],
  },

  // ============================================================
  // DÉFIS — Challenges et routines fun
  // ============================================================
  {
    category: "DÉFIS",
    title: "Challenge Core 5 min",
    intensity: "moderate",
    duration: "5 min",
    objective: "5 min pour forger des abdos en béton",
    focus: "strength",
    location: "home",
    equipment: [],
    tags: ["Challenge", "Core", "Rapide"],
    level: "Amateur / semi-pro",
    detail: [
      "Planche: 45\" — Sur les coudes, corps aligné de la tête aux pieds, gainage frontal",
      "Mountain climbers: 30\" — Position pompe, ramène les genoux vers la poitrine en alternant rapidement",
      "Planche latérale droite: 30\" — Sur le coude droit, corps aligné, hanche haute",
      "Planche latérale gauche: 30\" — Sur le coude gauche, corps aligné, hanche haute",
      "Dead bug: 30\" — Sur le dos, bras en l'air, alterne jambe/bras opposés sans cambrer",
      "Hollow hold: 30\" — Sur le dos, jambes et épaules décollées, bas du dos plaqué au sol",
      "Superman: 30\" — Sur le ventre, décolle bras et jambes en même temps, serre le dos",
      "Planche finale: 45\" — Dernière planche, tiens jusqu'au bout, finish strong",
    ],
    expectations: [
      "Pas de pause entre les exercices.",
      "Qualité de gainage > survie.",
      "Bats ton record la prochaine fois.",
    ],
  },
  {
    category: "DÉFIS",
    title: "Challenge Squats 100",
    intensity: "moderate",
    duration: "8-12 min",
    objective: "Le défi qui construit des jambes explosives",
    focus: "strength",
    location: "home",
    equipment: [],
    tags: ["Challenge", "Squats", "Endurance"],
    level: "Tout niveau",
    detail: [
      "Objectif: 100 squats poids du corps — Fais 100 squats le plus vite possible avec bonne forme",
      "Fractionne comme tu veux — Par exemple 10 x 10, 5 x 20, ou 4 x 25, adapte à ton niveau",
      "Repos minimal entre les séries — Juste le temps de reprendre ton souffle",
      "Profondeur: cuisses parallèles au sol — Pas de demi-squats, descends correctement",
      "Chronomètre ton temps total — Note-le pour battre ton record la prochaine fois",
    ],
    expectations: [
      "Forme correcte sur chaque rep.",
      "Note ton temps pour progresser.",
      "Objectif avancé: < 6 min.",
    ],
  },
  {
    category: "DÉFIS",
    title: "Test mobilité FKS",
    intensity: "easy",
    duration: "15 min",
    objective: "Découvre tes points faibles avant qu'ils te blessent",
    focus: "mobility",
    location: "home",
    equipment: [],
    tags: ["Test", "Évaluation", "Mobilité"],
    level: "Tout niveau",
    detail: [
      "Test dorsiflexion — Genou qui touche le mur sans lever le talon, note la distance pied-mur",
      "Test hanches — Squat complet talons au sol, note si tu y arrives et la position du buste",
      "Test T-spine — Allongé, bras écartés, tourne le buste, note si l'épaule touche le sol",
      "Test ischios — Debout, jambes tendues, penche vers les pieds, note la distance doigts-sol",
      "Test épaules — Une main par le haut, l'autre par le bas, essaie de les toucher dans le dos",
      "Note tout — Garde tes résultats pour voir ta progression dans 1 mois",
    ],
    expectations: [
      "Pas de forcing, juste évaluer.",
      "Refaire chaque mois.",
      "Identifier tes points faibles.",
    ],
  },
  {
    category: "DÉFIS",
    title: "Routine minimaliste 3 min",
    intensity: "easy",
    duration: "3 min",
    objective: "3 min chrono, zéro excuse, max de résultats",
    focus: "mobility",
    location: "home",
    equipment: [],
    tags: ["Express", "Minimal", "Quotidien"],
    level: "Tout niveau",
    detail: [
      "Cat-camel: 30\" — À 4 pattes, alterne dos rond puis dos creux, mobilise toute la colonne",
      "World's greatest stretch: 4 / côté — Fente avant + rotation du buste, bras vers le ciel",
      "Deep squat hold: 30\" — Squat complet, talons au sol, coudes écartent les genoux",
      "Standing hip circles: 8 / côté — Debout, genou levé, dessine des cercles avec le genou",
    ],
    expectations: [
      "Mieux que rien.",
      "Faire tous les jours si possible.",
      "3 min = aucune excuse.",
    ],
  },
];
